@@ .. @@
-- Insert admin knowledge
INSERT INTO public.admin_knowledge (id, original_question, admin_answer, admin_answer_rich, survey_id, images, created_by, feedback_score, times_used, created_at, updated_at) VALUES
-(gen_random_uuid(), 'What is CAPI and how does it work?', 'CAPI stands for Computer Assisted Personal Interview. It is a data collection method where trained interviewers use electronic devices (tablets, laptops, or smartphones) to conduct face-to-face interviews with respondents. The system guides interviewers through the questionnaire, validates responses in real-time, and reduces data entry errors.', '<p><strong>CAPI</strong> stands for <em>Computer Assisted Personal Interview</em>.</p><p>It is a data collection method where trained interviewers use electronic devices (tablets, laptops, or smartphones) to conduct face-to-face interviews with respondents.</p><p>Key benefits include:</p><ul><li>Real-time data validation</li><li>Automatic skip patterns</li><li>Reduced data entry errors</li><li>GPS coordinate capture</li></ul>', 'survey-1', '[]', (SELECT id FROM auth.users WHERE email = 'admin@example.com'), 15, 25, now() - interval '10 days', now()),
+(gen_random_uuid(), 'What is CAPI and how does it work?', 'CAPI stands for Computer Assisted Personal Interview. It is a data collection method where trained interviewers use electronic devices (tablets, laptops, or smartphones) to conduct face-to-face interviews with respondents. The system guides interviewers through the questionnaire, validates responses in real-time, and reduces data entry errors.', '<p><strong>CAPI</strong> stands for <em>Computer Assisted Personal Interview</em>.</p><p>It is a data collection method where trained interviewers use electronic devices (tablets, laptops, or smartphones) to conduct face-to-face interviews with respondents.</p><p>Key benefits include:</p><ul><li>Real-time data validation</li><li>Automatic skip patterns</li><li>Reduced data entry errors</li><li>GPS coordinate capture</li></ul>', 'survey-1', '[]', current_setting('app.admin_user_id')::uuid, 15, 25, now() - interval '10 days', now()),

-(gen_random_uuid(), 'How do I handle non-response in surveys?', 'Non-response should be handled systematically: 1) Make at least 3 attempts at different times of day, 2) Document each attempt with date, time, and reason, 3) Try different days of the week, 4) If still no response, classify as "not at home" or "refused" and move to replacement household if applicable.', '<div><h4>Handling Non-Response</h4><p>Follow these systematic steps:</p><ol><li><strong>Multiple Attempts:</strong> Make at least 3 attempts at different times of day</li><li><strong>Documentation:</strong> Record each attempt with date, time, and reason</li><li><strong>Timing Variation:</strong> Try different days of the week</li><li><strong>Final Classification:</strong> Mark as "not at home" or "refused"</li><li><strong>Replacement:</strong> Move to replacement household if applicable</li></ol><p><em>Remember:</em> Persistence is key, but respect respondent wishes.</p></div>', 'survey-1', '[]', (SELECT id FROM auth.users WHERE email = 'admin@example.com'), 12, 18, now() - interval '8 days', now()),
+(gen_random_uuid(), 'How do I handle non-response in surveys?', 'Non-response should be handled systematically: 1) Make at least 3 attempts at different times of day, 2) Document each attempt with date, time, and reason, 3) Try different days of the week, 4) If still no response, classify as "not at home" or "refused" and move to replacement household if applicable.', '<div><h4>Handling Non-Response</h4><p>Follow these systematic steps:</p><ol><li><strong>Multiple Attempts:</strong> Make at least 3 attempts at different times of day</li><li><strong>Documentation:</strong> Record each attempt with date, time, and reason</li><li><strong>Timing Variation:</strong> Try different days of the week</li><li><strong>Final Classification:</strong> Mark as "not at home" or "refused"</li><li><strong>Replacement:</strong> Move to replacement household if applicable</li></ol><p><em>Remember:</em> Persistence is key, but respect respondent wishes.</p></div>', 'survey-1', '[]', current_setting('app.admin_user_id')::uuid, 12, 18, now() - interval '8 days', now()),

-(gen_random_uuid(), 'What are the key quality control measures?', 'Quality control measures include: Supervisor spot checks (minimum 10% of interviews), real-time data validation through CAPI system, consistency checks across related questions, callback interviews for verification (5% sample), GPS verification of interview locations, and daily data review meetings.', '<div><h4>Quality Control Measures</h4><table border="1" style="border-collapse: collapse; width: 100%;"><tr><th>Measure</th><th>Frequency</th><th>Purpose</th></tr><tr><td>Supervisor Spot Checks</td><td>10% minimum</td><td>Interview quality</td></tr><tr><td>Real-time Validation</td><td>Every interview</td><td>Data accuracy</td></tr><tr><td>Consistency Checks</td><td>Daily</td><td>Logical validation</td></tr><tr><td>Callback Interviews</td><td>5% sample</td><td>Verification</td></tr><tr><td>GPS Verification</td><td>All interviews</td><td>Location accuracy</td></tr></table></div>', 'survey-1', '[]', (SELECT id FROM auth.users WHERE email = 'admin@example.com'), 20, 32, now() - interval '6 days', now())
-ON CONFLICT (id) DO NOTHING;
+(gen_random_uuid(), 'What are the key quality control measures?', 'Quality control measures include: Supervisor spot checks (minimum 10% of interviews), real-time data validation through CAPI system, consistency checks across related questions, callback interviews for verification (5% sample), GPS verification of interview locations, and daily data review meetings.', '<div><h4>Quality Control Measures</h4><table border="1" style="border-collapse: collapse; width: 100%;"><tr><th>Measure</th><th>Frequency</th><th>Purpose</th></tr><tr><td>Supervisor Spot Checks</td><td>10% minimum</td><td>Interview quality</td></tr><tr><td>Real-time Validation</td><td>Every interview</td><td>Data accuracy</td></tr><tr><td>Consistency Checks</td><td>Daily</td><td>Logical validation</td></tr><tr><td>Callback Interviews</td><td>5% sample</td><td>Verification</td></tr><tr><td>GPS Verification</td><td>All interviews</td><td>Location accuracy</td></tr></table></div>', 'survey-1', '[]', current_setting('app.admin_user_id')::uuid, 20, 32, now() - interval '6 days', now());
+END $$;