@@ .. @@
-- Insert chat messages
INSERT INTO public.chat_messages (id, session_id, content, rich_content, sender, feedback_type, feedback_provided, alternative_attempts, original_query, images, processing_time, confidence_score, created_at) VALUES
-(gen_random_uuid(), session1_id, 'What is CAPI?', NULL, 'user', NULL, false, 0, NULL, '[]', NULL, NULL, now() - interval '2 days'),
-(gen_random_uuid(), session1_id, 'CAPI stands for Computer Assisted Personal Interview. It is a data collection method where trained interviewers use electronic devices to conduct face-to-face interviews.', '<p><strong>CAPI</strong> stands for <em>Computer Assisted Personal Interview</em>. It is a data collection method where trained interviewers use electronic devices to conduct face-to-face interviews.</p>', 'admin', 'positive', true, 0, 'What is CAPI?', '[]', '00:00:02', 0.95, now() - interval '2 days'),
-(gen_random_uuid(), session1_id, 'How do I handle refusals?', NULL, 'user', NULL, false, 0, NULL, '[]', NULL, NULL, now() - interval '2 days'),
-(gen_random_uuid(), session1_id, 'When handling refusals, explain the importance of the survey and assure confidentiality. If they still refuse, mark as "refused" and move to the next household.', '<p>When handling refusals:</p><ol><li>Explain the importance of the survey</li><li>Assure confidentiality</li><li>If they still refuse, mark as "refused"</li><li>Move to the next household</li></ol>', 'bot', 'positive', true, 0, 'How do I handle refusals?', '[]', '00:00:03', 0.88, now() - interval '2 days'),
-(gen_random_uuid(), session2_id, 'What income sources should I ask about?', NULL, 'user', NULL, false, 0, NULL, '[]', NULL, NULL, now() - interval '1 day'),
-(gen_random_uuid(), session2_id, 'Ask about primary and secondary income sources, including employment, government transfers, benefits, and any other regular income.', '<p>Ask about these income sources:</p><ul><li>Primary employment income</li><li>Secondary income sources</li><li>Government transfers and benefits</li><li>Any other regular income</li></ul>', 'bot', 'positive', true, 0, 'What income sources should I ask about?', '[]', '00:00:02', 0.92, now() - interval '1 day')
+(gen_random_uuid(), current_setting('app.session1_id')::uuid, 'What is CAPI?', NULL, 'user', NULL, false, 0, NULL, '[]', NULL, NULL, now() - interval '2 days'),
+(gen_random_uuid(), current_setting('app.session1_id')::uuid, 'CAPI stands for Computer Assisted Personal Interview. It is a data collection method where trained interviewers use electronic devices to conduct face-to-face interviews.', '<p><strong>CAPI</strong> stands for <em>Computer Assisted Personal Interview</em>. It is a data collection method where trained interviewers use electronic devices to conduct face-to-face interviews.</p>', 'admin', 'positive', true, 0, 'What is CAPI?', '[]', '00:00:02', 0.95, now() - interval '2 days'),
+(gen_random_uuid(), current_setting('app.session1_id')::uuid, 'How do I handle refusals?', NULL, 'user', NULL, false, 0, NULL, '[]', NULL, NULL, now() - interval '2 days'),
+(gen_random_uuid(), current_setting('app.session1_id')::uuid, 'When handling refusals, explain the importance of the survey and assure confidentiality. If they still refuse, mark as "refused" and move to the next household.', '<p>When handling refusals:</p><ol><li>Explain the importance of the survey</li><li>Assure confidentiality</li><li>If they still refuse, mark as "refused"</li><li>Move to the next household</li></ol>', 'bot', 'positive', true, 0, 'How do I handle refusals?', '[]', '00:00:03', 0.88, now() - interval '2 days'),
+(gen_random_uuid(), current_setting('app.session2_id')::uuid, 'What income sources should I ask about?', NULL, 'user', NULL, false, 0, NULL, '[]', NULL, NULL, now() - interval '1 day'),
+(gen_random_uuid(), current_setting('app.session2_id')::uuid, 'Ask about primary and secondary income sources, including employment, government transfers, benefits, and any other regular income.', '<p>Ask about these income sources:</p><ul><li>Primary employment income</li><li>Secondary income sources</li><li>Government transfers and benefits</li><li>Any other regular income</li></ul>', 'bot', 'positive', true, 0, 'What income sources should I ask about?', '[]', '00:00:02', 0.92, now() - interval '1 day')
 ON CONFLICT (id) DO NOTHING;