@@ .. @@
-- Insert document chunks
+DO $$
+BEGIN
 INSERT INTO public.document_chunks (id, document_id, content, section, keywords, entities, word_count, character_count, content_type, importance, is_admin_answer, feedback_score, times_used, created_at, updated_at) VALUES
-(gen_random_uuid(), doc1_id, 'ENUMERATION PROCEDURES: Enumerators must follow these key steps: 1. Identify the household head 2. Complete the household roster 3. Ask questions in the prescribed order 4. Verify responses for consistency 5. Thank the respondent', 'Enumeration Procedures', ARRAY['enumeration', 'procedures', 'household', 'roster', 'questions'], ARRAY['Enumerators', 'Steps'], 32, 245, 'procedure', 2.0, false, 5, 12, now() - interval '5 days', now()),
+(gen_random_uuid(), current_setting('app.doc1_id')::uuid, 'ENUMERATION PROCEDURES: Enumerators must follow these key steps: 1. Identify the household head 2. Complete the household roster 3. Ask questions in the prescribed order 4. Verify responses for consistency 5. Thank the respondent', 'Enumeration Procedures', ARRAY['enumeration', 'procedures', 'household', 'roster', 'questions'], ARRAY['Enumerators', 'Steps'], 32, 245, 'procedure', 2.0, false, 5, 12, now() - interval '5 days', now()),

-(gen_random_uuid(), doc1_id, 'CAPI SYSTEM USAGE: The Computer Assisted Personal Interview (CAPI) system helps ensure data quality through: - Automatic skip patterns - Range checks for numeric fields - Consistency validations - GPS coordinate capture', 'CAPI System', ARRAY['capi', 'computer', 'interview', 'data', 'quality', 'validation'], ARRAY['CAPI', 'GPS'], 28, 198, 'definition', 2.5, false, 8, 18, now() - interval '5 days', now()),
+(gen_random_uuid(), current_setting('app.doc1_id')::uuid, 'CAPI SYSTEM USAGE: The Computer Assisted Personal Interview (CAPI) system helps ensure data quality through: - Automatic skip patterns - Range checks for numeric fields - Consistency validations - GPS coordinate capture', 'CAPI System', ARRAY['capi', 'computer', 'interview', 'data', 'quality', 'validation'], ARRAY['CAPI', 'GPS'], 28, 198, 'definition', 2.5, false, 8, 18, now() - interval '5 days', now()),

-(gen_random_uuid(), doc2_id, 'INCOME QUESTIONS: When asking about household income: - Start with employment status of all members - Ask about primary and secondary income sources - Include government transfers and benefits - Verify amounts and frequency', 'Income Questions', ARRAY['income', 'employment', 'household', 'benefits', 'transfers'], ARRAY['Government'], 26, 187, 'procedure', 1.8, false, 3, 8, now() - interval '4 days', now()),
+(gen_random_uuid(), current_setting('app.doc2_id')::uuid, 'INCOME QUESTIONS: When asking about household income: - Start with employment status of all members - Ask about primary and secondary income sources - Include government transfers and benefits - Verify amounts and frequency', 'Income Questions', ARRAY['income', 'employment', 'household', 'benefits', 'transfers'], ARRAY['Government'], 26, 187, 'procedure', 1.8, false, 3, 8, now() - interval '4 days', now()),

-(gen_random_uuid(), doc3_id, 'HEALTH STATUS DATA: Member ID, General Health, Chronic Conditions, Disability Status, Healthcare Access. Example: M01, Good, Diabetes, None, Yes', 'Health Status', ARRAY['health', 'chronic', 'conditions', 'disability', 'healthcare'], ARRAY['Diabetes'], 18, 134, 'data', 1.5, false, 2, 5, now() - interval '3 days', now()),
+(gen_random_uuid(), current_setting('app.doc3_id')::uuid, 'HEALTH STATUS DATA: Member ID, General Health, Chronic Conditions, Disability Status, Healthcare Access. Example: M01, Good, Diabetes, None, Yes', 'Health Status', ARRAY['health', 'chronic', 'conditions', 'disability', 'healthcare'], ARRAY['Diabetes'], 18, 134, 'data', 1.5, false, 2, 5, now() - interval '3 days', now()),

-(gen_random_uuid(), doc4_id, 'SURVEY OBJECTIVES: The Education Access Survey aims to: - Assess enrollment rates across different education levels - Identify barriers to educational access - Evaluate quality of educational services - Measure learning outcomes', 'Survey Objectives', ARRAY['education', 'enrollment', 'access', 'quality', 'learning'], ARRAY['Education Access Survey'], 24, 178, 'definition', 2.2, false, 6, 14, now() - interval '2 days', now()),
+(gen_random_uuid(), current_setting('app.doc4_id')::uuid, 'SURVEY OBJECTIVES: The Education Access Survey aims to: - Assess enrollment rates across different education levels - Identify barriers to educational access - Evaluate quality of educational services - Measure learning outcomes', 'Survey Objectives', ARRAY['education', 'enrollment', 'access', 'quality', 'learning'], ARRAY['Education Access Survey'], 24, 178, 'definition', 2.2, false, 6, 14, now() - interval '2 days', now()),

-(gen_random_uuid(), doc4_id, 'INTERVIEW TECHNIQUES: Best practices for education surveys: - Use age-appropriate language for children - Ensure privacy for sensitive questions - Verify school records when possible - Ask about both formal and informal education', 'Interview Techniques', ARRAY['interview', 'techniques', 'children', 'privacy', 'education'], ARRAY['School'], 22, 165, 'procedure', 1.9, false, 4, 9, now() - interval '2 days', now()),
+(gen_random_uuid(), current_setting('app.doc4_id')::uuid, 'INTERVIEW TECHNIQUES: Best practices for education surveys: - Use age-appropriate language for children - Ensure privacy for sensitive questions - Verify school records when possible - Ask about both formal and informal education', 'Interview Techniques', ARRAY['interview', 'techniques', 'children', 'privacy', 'education'], ARRAY['School'], 22, 165, 'procedure', 1.9, false, 4, 9, now() - interval '2 days', now()),

-(gen_random_uuid(), doc1_id, 'COMMON ISSUES: Q: What if a respondent refuses to answer? A: Explain the importance of the census and assure confidentiality. If they still refuse, mark as "refused" and move to the next household.', 'Common Issues', ARRAY['respondent', 'refuses', 'confidentiality', 'census'], ARRAY['Census'], 28, 189, 'qa', 2.1, false, 7, 16, now() - interval '5 days', now())
-ON CONFLICT (id) DO NOTHING;
+(gen_random_uuid(), current_setting('app.doc1_id')::uuid, 'COMMON ISSUES: Q: What if a respondent refuses to answer? A: Explain the importance of the census and assure confidentiality. If they still refuse, mark as "refused" and move to the next household.', 'Common Issues', ARRAY['respondent', 'refuses', 'confidentiality', 'census'], ARRAY['Census'], 28, 189, 'qa', 2.1, false, 7, 16, now() - interval '5 days', now());
+END $$;